name: ddm-language-server
replicaCount: 1

image:
  name: ddm-language-server
  version: latest

serviceAccount:
  create: true
  annotations: {}
  name: ddm-language-server

service:
  type: ClusterIP
  port: 8080

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness

keycloak:
  realms:
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs
