apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    {{- if eq .Values.global.deploymentMode "production" }}
    cors.allowed-origin-patterns: '{{- include "admin-tools.url" (dict "root" $) }}'
    {{- else }}
    cors.allowed-origin-patterns: '*'
    {{- end }}
    socket.message-size: 30000
