apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "ddm-language-server.serviceAccountName" . }}-edp
roleRef:
    kind: Role
    name: edp-{{ include "ddm-language-server.serviceAccountName" . }}-role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: {{ include "ddm-language-server.serviceAccountName" . }}
